import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <header className="flex justify-between items-center bg-orange-200 h-16 w-full">
        <Image className="pl-12" src="next.svg" width={130} height={150} alt=""/>
        <nav className="flex gap-10 pr-12 text-xl font-medium hover:font-semibold">
          <Link href={"/"}>Home</Link>
          <Link href={""}>Endereços</Link>
        </nav>
      </header>
      </body>
    </html>
  );
}
